name: Deploy MERN To-Do App

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy-frontend:
    name: Deploy React Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "client/build"

  deploy-backend:
    name: Deploy Node.js Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Copy Backend Files to EC2
        run: |
          echo "Copying backend files to EC2..."
          scp -i ${{ secrets.AWS_PRIVATE_KEY }} -r server ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/ToDo-App/


      - name: Restart Server on EC2
        run: |
          ssh -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/ToDo-app
          npm install
          pm2 restart all || pm2 start index.js --name "todo-api"
          EOF
