name: Generate Project Structure

on: 
  push:
    branches:
      - main  # Runs only on the main branch

jobs:
  list-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Install tree
        run: sudo apt-get install tree -y  # Install tree if not available

      - name: Generate project structure
        run: |
          tree -L 4 > project-structure.txt
          cat project-structure.txt

      - name: Upload as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: project-structure
          path: project-structure.txt
