name: Generate Project Structure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Install tree
      run: sudo apt-get install -y tree
      
    - name: Generate File Tree
      run: tree -a -I "node_modules|build|.git" > project-structure.txt
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-structure
        path: project-structure.txt
